[rospy.client][INFO] 2020-09-01 10:18:37,786: init_node, name[/diagnostic_map_scan_rear], pid[20989]
[xmlrpc][INFO] 2020-09-01 10:18:37,786: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-09-01 10:18:37,786: Started XML-RPC server [http://cuboid:36491/]
[rospy.init][INFO] 2020-09-01 10:18:37,786: ROS Slave URI: [http://cuboid:36491/]
[rospy.impl.masterslave][INFO] 2020-09-01 10:18:37,787: _ready: http://cuboid:36491/
[xmlrpc][INFO] 2020-09-01 10:18:37,787: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-09-01 10:18:37,787: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-09-01 10:18:37,887: registered with master
[rospy.rosout][INFO] 2020-09-01 10:18:37,887: initializing /rosout core topic
[rospy.rosout][INFO] 2020-09-01 10:18:37,889: connected to core topic /rosout
[rospy.simtime][INFO] 2020-09-01 10:18:37,891: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-09-01 10:18:37,903: topic[/map_scan_rear] adding connection to [http://cuboid:37987/], count 0
[rospy.internal][INFO] 2020-09-01 10:18:38,037: topic[/diagnostics] adding connection to [/diag_agg], count 0
[rospy.internal][INFO] 2020-09-01 10:18:38,140: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-09-01 10:25:42,036: topic[/diagnostics] removing connection to /diag_agg
[rospy.impl.masterslave][INFO] 2020-09-01 10:25:42,378: external shutdown request from [/rosnode]: user request
[rospy.core][INFO] 2020-09-01 10:25:42,378: signal_shutdown [external shutdown request from [/rosnode]: [user request]]
[rospy.internal][INFO] 2020-09-01 10:25:42,380: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-09-01 10:25:42,380: topic[/map_scan_rear] removing connection to http://cuboid:37987/
[rospy.internal][WARNING] 2020-09-01 10:25:42,381: Unknown error initiating TCP/IP socket to cuboid:59671 (http://cuboid:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2020-09-01 10:25:42,381: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.core][INFO] 2020-09-01 10:25:42,748: signal_shutdown [atexit]
