[rospy.client][INFO] 2020-09-10 10:15:09,682: init_node, name[/diagnostic_imu_topic], pid[5571]
[xmlrpc][INFO] 2020-09-10 10:15:09,682: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-09-10 10:15:09,682: Started XML-RPC server [http://cuboid0009:40293/]
[rospy.init][INFO] 2020-09-10 10:15:09,683: ROS Slave URI: [http://cuboid0009:40293/]
[rospy.impl.masterslave][INFO] 2020-09-10 10:15:09,683: _ready: http://cuboid0009:40293/
[rospy.registration][INFO] 2020-09-10 10:15:09,683: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-09-10 10:15:09,684: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-09-10 10:15:09,783: registered with master
[rospy.rosout][INFO] 2020-09-10 10:15:09,783: initializing /rosout core topic
[rospy.rosout][INFO] 2020-09-10 10:15:09,785: connected to core topic /rosout
[rospy.simtime][INFO] 2020-09-10 10:15:09,786: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-09-10 10:15:09,798: topic[/gyro/imu] adding connection to [http://cuboid0009:41741/], count 0
[rospy.internal][INFO] 2020-09-10 10:15:09,999: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-09-10 10:15:10,000: topic[/diagnostics] adding connection to [/diag_agg], count 0
[rospy.impl.masterslave][INFO] 2020-09-10 10:19:42,338: external shutdown request from [/rosnode]: user request
[rospy.core][INFO] 2020-09-10 10:19:42,338: signal_shutdown [external shutdown request from [/rosnode]: [user request]]
[rospy.internal][INFO] 2020-09-10 10:19:42,341: topic[/diagnostics] removing connection to /diag_agg
[rospy.internal][INFO] 2020-09-10 10:19:42,341: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-09-10 10:19:42,341: topic[/gyro/imu] removing connection to http://cuboid0009:41741/
[rospy.topics][ERROR] 2020-09-10 10:19:42,342: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][WARNING] 2020-09-10 10:19:42,342: Unknown error initiating TCP/IP socket to cuboid0009:55171 (http://cuboid0009:41741/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-09-10 10:19:42,525: signal_shutdown [atexit]
