[rospy.client][INFO] 2020-09-10 14:01:26,663: init_node, name[/diagnostic_rplidar_head_topic], pid[8888]
[xmlrpc][INFO] 2020-09-10 14:01:26,664: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-09-10 14:01:26,664: Started XML-RPC server [http://cuboid0009:35359/]
[rospy.init][INFO] 2020-09-10 14:01:26,664: ROS Slave URI: [http://cuboid0009:35359/]
[rospy.impl.masterslave][INFO] 2020-09-10 14:01:26,664: _ready: http://cuboid0009:35359/
[rospy.registration][INFO] 2020-09-10 14:01:26,665: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-09-10 14:01:26,665: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-09-10 14:01:26,765: registered with master
[rospy.rosout][INFO] 2020-09-10 14:01:26,765: initializing /rosout core topic
[rospy.rosout][INFO] 2020-09-10 14:01:26,767: connected to core topic /rosout
[rospy.simtime][INFO] 2020-09-10 14:01:26,768: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-09-10 14:01:26,780: topic[/head_scan] adding connection to [http://cuboid0009:39189/], count 0
[rospy.internal][INFO] 2020-09-10 14:01:27,044: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-09-10 14:01:27,045: topic[/diagnostics] adding connection to [/diag_agg], count 0
[rospy.internal][INFO] 2020-09-10 14:20:11,137: topic[/diagnostics] removing connection to /diag_agg
[rospy.impl.masterslave][INFO] 2020-09-10 14:20:12,303: external shutdown request from [/rosnode]: user request
[rospy.core][INFO] 2020-09-10 14:20:12,303: signal_shutdown [external shutdown request from [/rosnode]: [user request]]
[rospy.internal][INFO] 2020-09-10 14:20:12,306: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-09-10 14:20:12,306: topic[/head_scan] removing connection to http://cuboid0009:39189/
[rospy.topics][ERROR] 2020-09-10 14:20:12,307: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][WARNING] 2020-09-10 14:20:12,307: Unknown error initiating TCP/IP socket to cuboid0009:38531 (http://cuboid0009:39189/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-09-10 14:20:12,718: signal_shutdown [atexit]
